import type { OrderStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { idr, requireAdmin } from "../_helpers";

export default async function AdminOrdersPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  await requireAdmin();
  const { status } = await searchParams;
  const allowedStatuses = new Set(["PENDING", "PROCESSING", "COMPLETED", "CANCELLED"]);
  const statusFilter = status && allowedStatuses.has(status) ? (status as OrderStatus) : undefined;
  const orders = await prisma.order.findMany({ where: statusFilter ? { status: statusFilter } : undefined, include: { user: { select: { name: true, email: true, phone: true } }, payments: { select: { provider: true, status: true, amount: true, currency: true, paidAt: true } } }, orderBy: { createdAt: "desc" }, take: 50 });
  const failedConversions = await prisma.conversionJob.findMany({ where: { status: "FAILED" }, select: { id: true, userId: true, originalFilename: true, costCoins: true, errorReason: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 20 });
  return <main className="section"><h1 className="text-4xl font-black">Admin Pesanan & Konversi</h1><p className="muted mt-3">Audit pesanan, pembayaran terkait, dan konversi gagal dengan data nyata.</p><section className="mt-8 glass rounded-3xl p-5"><h2 className="text-2xl font-bold">Pesanan</h2><div className="mt-4 space-y-3">{orders.map((order) => <article className="rounded-2xl border border-white/10 p-4 text-sm" key={order.id}><div className="flex flex-col justify-between gap-2 lg:flex-row"><p className="font-semibold">{order.title} · {order.status}</p><p>{idr(order.amount)}</p></div><p className="muted">{order.user.name ?? order.user.email ?? order.user.phone ?? "Pengguna"} · {order.createdAt.toLocaleString("id-ID")}</p>{order.payments.map((payment) => <p className="muted mt-1" key={`${order.id}-${payment.provider}-${payment.status}`}>{payment.provider} · {payment.status} · {idr(payment.amount)}</p>)}</article>)}{orders.length === 0 && <p className="muted">Belum ada pesanan.</p>}</div></section><section className="mt-8 glass rounded-3xl p-5"><h2 className="text-2xl font-bold">Konversi Gagal</h2><div className="mt-4 space-y-3">{failedConversions.map((job) => <article className="rounded-2xl border border-white/10 p-4 text-sm" key={job.id}><p className="font-semibold">{job.originalFilename} · {job.costCoins} Coin</p><p className="muted">{job.createdAt.toLocaleString("id-ID")} · {job.errorReason ?? "Alasan tidak tersedia"}</p></article>)}{failedConversions.length === 0 && <p className="muted">Tidak ada konversi gagal.</p>}</div></section></main>;
}
