import { prisma } from "@/lib/prisma";
import { idr, requireAdmin } from "../_helpers";

export default async function AdminPaymentsPage() {
  await requireAdmin();
  const [payments, coinTransactions] = await Promise.all([
    prisma.payment.findMany({ include: { user: { select: { name: true, email: true, phone: true } }, order: { select: { title: true, status: true } } }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.coinTransaction.findMany({ include: { user: { select: { name: true, email: true, phone: true } }, admin: { select: { name: true, email: true } } }, orderBy: { createdAt: "desc" }, take: 50 }),
  ]);
  return <main className="section"><h1 className="text-4xl font-black">Admin Pembayaran & Coin</h1><p className="muted mt-3">Audit pembayaran dan ledger Coin. External ID hanya ditampilkan ringkas untuk operasional, bukan token rahasia.</p><section className="mt-8 glass rounded-3xl p-5"><h2 className="text-2xl font-bold">Pembayaran</h2><div className="mt-4 space-y-3">{payments.map((payment) => <article className="rounded-2xl border border-white/10 p-4 text-sm" key={payment.id}><div className="flex flex-col justify-between gap-2 lg:flex-row"><p className="font-semibold">{payment.order.title} · {payment.status}</p><p>{idr(payment.amount)}</p></div><p className="muted">{payment.user.name ?? payment.user.email ?? payment.user.phone ?? "Pengguna"} · {payment.provider} · {payment.method}</p><p className="muted">Ref: {payment.externalId ? `${payment.externalId.slice(0, 16)}…` : "—"}</p></article>)}{payments.length === 0 && <p className="muted">Belum ada pembayaran.</p>}</div></section><section className="mt-8 glass rounded-3xl p-5"><h2 className="text-2xl font-bold">Transaksi Coin</h2><div className="mt-4 space-y-3">{coinTransactions.map((tx) => <article className="rounded-2xl border border-white/10 p-4 text-sm" key={tx.id}><div className="flex flex-col justify-between gap-2 lg:flex-row"><p className="font-semibold">{tx.description}</p><p className={tx.amount > 0 ? "text-emerald-300" : "text-amber-300"}>{tx.amount > 0 ? "+" : ""}{tx.amount} Coin</p></div><p className="muted">{tx.user.name ?? tx.user.email ?? tx.user.phone ?? "Pengguna"} · {tx.type} · {tx.status}</p>{tx.admin && <p className="muted">Admin: {tx.admin.name ?? tx.admin.email}</p>}</article>)}{coinTransactions.length === 0 && <p className="muted">Belum ada transaksi Coin.</p>}</div></section></main>;
}
